import {createContext,useContext,useEffect,useReducer,ReactNode} from 'react';
import type {JourneyState,PartnerId,PartnerResponse,Role,JourneyMode,MirrorAssessment,PauseCheckValue,PartnerFeedback} from '../types/journey';
export const STORAGE_KEY='weddingos-prototype-v1';
export const MIRROR_TEXT='You appear to share commitment, while the meaning of timing still deserves conversation.';
export const initialState:JourneyState={role:'partner-a',partners:{'partner-a':{preparationStatus:'not-started',responses:{}},'partner-b':{preparationStatus:'not-started',responses:{}}},shared:{mode:'core',stage:'welcome',bridgeApprovals:[],discoveries:{},mirror:{generatedText:MIRROR_TEXT,corrections:{},saveApproved:false}}};
export type Action={type:'role';role:Role}|{type:'mode';mode:JourneyMode}|{type:'response';partner:PartnerId;response:PartnerResponse}|{type:'status';partner:PartnerId;status:PartnerStateStatus}|{type:'stage';stage:string;path?:string}|{type:'approve-bridge';partner:PartnerId}|{type:'discoveries';values:JourneyState['shared']['discoveries']}|{type:'integration';partner:PartnerId;values:NonNullable<JourneyState['partners'][PartnerId]['integration']>}|{type:'notes';value:string}|{type:'mirror-assessment';value:MirrorAssessment}|{type:'mirror-correction';kind:'partly'|'not-quite';value:string}|{type:'pause-check';value:PauseCheckValue}|{type:'feedback';partner:PartnerId;values:PartnerFeedback}|{type:'reset'};
type PartnerStateStatus=JourneyState['partners'][PartnerId]['preparationStatus'];
export function reducer(state:JourneyState,a:Action):JourneyState{switch(a.type){case'role':return{...state,role:a.role};case'mode':return{...state,shared:{...state.shared,mode:a.mode}};case'response':return{...state,partners:{...state.partners,[a.partner]:{...state.partners[a.partner],preparationStatus:'in-progress',responses:{...state.partners[a.partner].responses,[a.response.promptId]:a.response}}}};case'status':return{...state,partners:{...state.partners,[a.partner]:{...state.partners[a.partner],preparationStatus:a.status}}};case'stage':return{...state,shared:{...state.shared,stage:a.stage,previousPath:a.path??state.shared.previousPath}};case'approve-bridge':return state.shared.bridgeApprovals.includes(a.partner)?state:{...state,shared:{...state.shared,bridgeApprovals:[...state.shared.bridgeApprovals,a.partner]}};case'discoveries':return{...state,shared:{...state.shared,discoveries:a.values}};case'integration':return{...state,partners:{...state.partners,[a.partner]:{...state.partners[a.partner],integration:a.values}}};case'notes':return{...state,shared:{...state.shared,sharedNotes:a.value}};case'mirror-assessment':{const correction=a.value==='not-quite'?state.shared.mirror.corrections[a.value]?.trim():'';const saveApproved=a.value==='reflects'||a.value==='partly'||(a.value==='not-quite'&&Boolean(correction));return{...state,shared:{...state.shared,mirror:{...state.shared.mirror,assessment:a.value,saveApproved}}}}case'mirror-correction':return{...state,shared:{...state.shared,mirror:{...state.shared.mirror,corrections:{...state.shared.mirror.corrections,[a.kind]:a.value},saveApproved:state.shared.mirror.assessment==='partly'||(state.shared.mirror.assessment==='not-quite'&&Boolean(a.value.trim()))}}};case'pause-check':return{...state,shared:{...state.shared,pauseCheck:a.value}};case'feedback':return{...state,partners:{...state.partners,[a.partner]:{...state.partners[a.partner],feedback:a.values}}};case'reset':return initialState;}}
const C=createContext<{state:JourneyState;dispatch:React.Dispatch<Action>}|null>(null);
export function JourneyProvider({children}:{children:ReactNode}){const [state,dispatch]=useReducer(reducer,initialState,s=>{try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'') as Partial<JourneyState>;return{...s,...saved,partners:{...s.partners,...saved.partners},shared:{...s.shared,...saved.shared,discoveries:{...s.shared.discoveries,...saved.shared?.discoveries},mirror:{...s.shared.mirror,...saved.shared?.mirror,corrections:{...s.shared.mirror.corrections,...saved.shared?.mirror?.corrections}}}}}catch{return s}});useEffect(()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state)),[state]);return <C.Provider value={{state,dispatch}}>{children}</C.Provider>}
export function useJourney(){const v=useContext(C);if(!v)throw new Error('JourneyProvider missing');return v}
export function approvedContent(state:JourneyState){return (Object.values(state.partners) as JourneyState['partners'][PartnerId][]).flatMap(p=>Object.values(p.responses)).filter(r=>r.sharingLevel==='share-exact'||(r.sharingLevel==='summary-requested'&&r.approvedSummary)).map(r=>r.approvedSummary||r.responseText||'')}
export function bridgeFor(state:JourneyState){const n=approvedContent(state).length;return n>=2?'You both described meaningful parts of married life that you feel ready to enter. Tonight’s conversation will explore what becoming spouses means to each of you—and whether uncertainty is mainly about marriage or the celebration surrounding it.':n===1?'You both appear committed to marriage, while timing may hold different meaning. Tonight is about understanding what each of you hopes to preserve, not determining whose interpretation is correct.':'You have both completed your private preparation. Tonight’s conversation will begin without a summary. Each of you can explain what becoming married means in your own words.'}
export function approvedMirror(state:JourneyState){const m=state.shared.mirror;if(!m.saveApproved)return undefined;if(m.assessment==='reflects')return m.generatedText;if(m.assessment==='partly')return m.corrections.partly?.trim();if(m.assessment==='not-quite')return m.corrections['not-quite']?.trim();return undefined}
